name: Deploy Blog Website to Render

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FLASK_APP: backend.wsgi
  PYTHON_VERSION: '3.10'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd backend
          python -m pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd backend
          pip install -r requirements.txt
          pip install gunicorn

      - name: Run database migrations
        run: |
          cd backend
          python -m flask db upgrade

      - name: Deploy to Render
        uses: render-actions/deploy@v2
        with:
          renderToken: ${{ secrets.RENDER_TOKEN }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          branch: main
          waitForDeploy: true
          skipStaticBuild: true
